###
# SCIZ Nginx configuration
# (Only things not set by default)
###

##
# Additional HTTP configurations
##

# Disable tokens for production
server_tokens off;
more_clear_headers "Server" "X-Powered-By";

# Store the logs of passenger in a specific file
passenger_log_file /var/log/nginx/passenger.log;

##
# Main VHOST
##

server {
    server_name	sciz.fr;
    listen	80;
    listen	443 ssl;
    return	301 https://www.sciz.fr$request_uri;
}

server {
    server_name www.sciz.fr;
    root /sciz/web/dist-public/;

    ##
    # CORS - FOR DEBUG ONLY
    ##
    #add_header 'Access-Control-Allow-Origin' '*' always;
    #add_header 'Access-Control-Allow-Credentials' 'true' always;
    #add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
    
    ##
    # HTTP
    ##
    listen 80;
    listen [::]:80 ipv6only=on;
    if ($scheme != "https") {
      return 301 https://$host$request_uri;
    }
    
    ##
    # HTTPS
    ##
    listen 443 ssl default_server;
    listen [::]:443 ipv6only=on ssl default_server;
    
    # SSL/TLS
    ssl_certificate "/etc/letsencrypt/live/sciz.fr/fullchain.pem";
    ssl_certificate_key "/etc/letsencrypt/live/sciz.fr/privkey.pem";
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Proxy requests to Flask through Phusion Passenger 
    passenger_enabled on;
    passenger_python /usr/bin/python3;
    passenger_app_type wsgi;
    passenger_app_root /sciz;
    passenger_startup_file sciz.py;
    
    # Static files are served directly and requests are not forwarded to flask python app
    location ^~ /static/  {
        include /etc/nginx/mime.types;
    }
    location ^~ /api/ {
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        add_header 'Access-Control-Allow-Origin' $http_origin always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        add_header 'Access-Control-Allow-Request' 'GET, POST' always;
        add_header 'Access-Control-Max-Age' '600' always;
        expires off;
    }
    location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
    }

    # Do not show any error
    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 500 501 502 503 504 505 506 507 508 509 510 511 default.html;

    # Logging
    access_log /var/log/nginx/access-sciz.log;
    error_log  /var/log/nginx/error-sciz.log;
}
